# Create a model that can preedict the profit of the company on the basis of company's spending pattern and company's location

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('50_Startups.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [4]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
data.State.unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [5]:
features = data.iloc[:,:-1].values
label = data.iloc[:,-1].values

In [7]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
fState=ohe.fit_transform(features[:,3].reshape(-1,1))
fState

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [8]:
finalFeatureSet = np.concatenate((fState,features[:,[0,1,2]]) , axis=1)
finalFeatureSet

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(finalFeatureSet,
                                                label,
                                                test_size=0.2,
                                                random_state=1)

In [10]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [11]:
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.942446542689397
0.9649618042060378


In [ ]:
X_train[0]

array([1.0, 0.0, 0.0, 63408.86, 129219.61, 46085.25], dtype=object)

In [ ]:
ohe.categories_

[array(['California', 'Florida', 'New York'], dtype=object)]

In [ ]:
#Deploy Test

#R&D Spend	Administration	Marketing Spend	State

rdSpend = float(input("Enter R&D :"))
admSpend = float(input("Enter Administration Spend: "))
markSpend = float(input("Enter Marketing Spend: "))
state = input("Enter State: ")

if state not in list(ohe.categories_)[0]:
    print("State not known by AI master :( ")
else:
    stateDummy = ohe.transform(np.array([[state]]))
    compatibleFeatureSet = np.concatenate((stateDummy,np.array([[rdSpend,admSpend,markSpend]])), axis=1)
    profit=model.predict(compatibleFeatureSet)[0]
    print("Predicted Profit is : ",profit)



Enter R&D :234567
Enter Administration Spend: 234567
Enter Marketing Spend: 76543
Enter State: New York
Predicted Profit is :  231455.91595556875


In [12]:
#Save the model
import pickle

#Dumping Model -- Used for prediction
pickle.dump(model,open('ProfitPredictor.pkl','wb'))

#Dumping OHE object --- Used to convert categorical data to its equivalent dummy variable
pickle.dump(ohe,open('StateEncoder.pkl','wb'))

In [13]:
import sklearn
sklearn.__version__

'1.6.1'